### ISSUE TITLE
How is it different than infinite-scroll-x ??

### ISSUE THREAD

**Issue by deadcoder0904** [lexor90/react-native-infinite-scroll#2]

**Comment by lexor90** [comment]
Hi there,
there are a couple of improvements.

First off it's based upon the newer react native component creation ("extends Component" rather than the older "createClass") – you'd get errors without updating this with any recent react version.

Second you can control the `distanceFromEnd` property telling it how much, before to reach the end, you should be preloading the next items. Useful when you use it to display multiple elements (e.g. the original library had a default of 5idp which was nothing compared to the size and load time of the elements I was displaying).

Let me know if this answers your question.

**Comment by deadcoder0904** [comment]
Woah, that was quick!! Nice explanation, thanks!! 💯 
I'll keep it open incase someone wonders 😝 
Close it if you want 😄
